name: Daily PACE Ocean Update

on:
  schedule:
    # Run 4 times per day: 3am, 9am, 3pm, 9pm UTC
    - cron: '0 3,9,15,21 * * *'
  
  # Allow manual trigger
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Configure Git
      run: |
        git config --local user.email "duc.dut.wr@gmail.com"
        git config --local user.name "ductran27"
    
    - name: Run PACE monitoring script
      run: |
        python main.py
    
    - name: Commit and push if changes
      run: |
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Daily PACE ocean update: $(date +'%Y-%m-%d')"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
